name: srs
channels:
  - defaults
#  - mlsg
dependencies:
  - configparser
  - numpy
  - lxml
  - nltk
  - scipy
  - matplotlib
  - flask
  - pandas
  - bokeh
  - vaderSentiment
#  - fake_useragent
#  - amazon_scraper